name: llmops
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - numpy
    - pandas
    - ipykernel
    - azure-ai-ml
    - azure-identity
    - azureai-contentsafety
    - pillow
    - wheel
    - python-dotenv
    - azureml-fsspec
    - azureml-mlflow
    - promptflow
    - promptflow-tools
    - keyrings.alt
    - bs4